Repository VIAplanner/via-timetable, pull requests merged in 2020-07, with the labels that each got.

#224 Api Vulnerability Fix
  packages/app/src/components/AppBar/CourseSearchBar.vue
  packages/courses-scraper/api/node/uploader.js
  packages/courses-scraper/api/python/uploader.py
  packages/unified-backend/src/index.js
  packages/unified-backend/src/routes/course.js
Labels: V2, critical

#230 API Update
  packages/app/package.json
  packages/app/src/components/AppBar/CourseSearchBar.vue
  packages/app/vue.config.js
  packages/courses-scraper/api/node/scraper.js
  packages/courses-scraper/api/node/uploader.js
  packages/courses-scraper/package.json
  packages/unified-backend/package-lock.json
  packages/unified-backend/package.json
  packages/unified-backend/src/index.js
  packages/unified-backend/src/routes/course.js
Labels: V2, enhancement

#233 Scaling bug fix
  packages/app/src/components/SidePanel/SideBar.vue
  packages/app/src/components/Timetable/Timetable.vue
  packages/app/src/components/Timetable/TimetableEvent.vue
  packages/app/src/views/Home.vue
Labels: V2, bug

#234 Save user timetable in browser
  packages/app/src/store/index.js
  packages/app/src/views/Home.vue
Labels: V2, enhancement

#253 Bug fixes 7/12/2020
  packages/app/src/components/AppBar/DeliveryMethodSetting.vue
  packages/app/src/components/Popup/CourseSectionPicker.vue
  packages/app/src/components/SidePanel/SideBar.vue
  packages/app/src/components/Timetable/HourSwitch.vue
  packages/app/src/components/Timetable/Timetable.vue
  packages/app/src/components/Timetable/TimetableEvent.vue
  packages/app/src/components/Timetable/WeekdaySwitch.vue
  packages/app/src/store/index.js
  packages/app/src/timetable-planner/index.js
  packages/app/src/views/Timetable.vue
Labels: bug, clean up, enhancement

#254 Fixed export bug
  packages/app/src/components/Timetable/Timetable.vue
Labels: V2, bug

#259 Completed Tri-Campus Integration
  packages/app/src/components/AppBar/CourseSearchBar.vue
  packages/courses-scraper/.babelrc
  packages/courses-scraper/api/node/structures/course.js
  packages/courses-scraper/api/node/structures/meetingSection.js
  packages/courses-scraper/api/node/structures/time.js
  packages/courses-scraper/api/node/tri-campus/scrape-code.js
  packages/courses-scraper/api/node/tri-campus/scraper.js
  packages/courses-scraper/api/node/uploader-native.js
  packages/courses-scraper/api/node/uploader.js
  packages/courses-scraper/api/node/utm/scraper.js
  packages/courses-scraper/package-lock.json
  packages/courses-scraper/package.json
  packages/unified-backend/package-lock.json
  packages/unified-backend/package.json
  packages/unified-backend/src/index.js
  packages/unified-backend/src/models/course.js
Labels: V2, enhancement

#265 Cache improvement
  packages/app/src/components/AppBar/CourseSearchBar.vue
  packages/app/src/store/index.js
  packages/app/src/views/About.vue
  packages/app/src/views/Home.vue
Labels: V2, bug, enhancement

#268 Recent Issue Fix
  packages/app/package-lock.json
  packages/app/package.json
  packages/app/src/components/AppBar/CourseSearchBar.vue
  packages/app/src/components/Popup/CourseSectionPicker.vue
  packages/app/src/components/SidePanel/SelectedCourseCard.vue
  packages/app/src/components/SidePanel/SideBar.vue
  packages/app/src/components/Timetable/TimetableEvent.vue
  packages/app/src/store/index.js
  packages/app/src/timetable-planner/index.js
  packages/app/src/views/Home.vue
  packages/courses-scraper/api/node/tri-campus/scraper.js
  packages/courses-scraper/api/node/uploaders/uploader-native.js
  packages/courses-scraper/api/node/uploaders/uploader.js
  packages/courses-scraper/api/node/verifiers/utm-verifier.js
  packages/courses-scraper/package.json
Labels: V2, bug

#269 Course code exception fix
  packages/app/src/components/AppBar/CourseSearchBar.vue
  packages/app/src/store/index.js
  packages/courses-scraper/api/node/structures/course.js
  packages/courses-scraper/api/node/tri-campus/scraper.js
  packages/courses-scraper/api/node/uploaders/uploader-native.js
  packages/unified-backend/src/models/searchbar.js
  packages/unified-backend/src/routes/course.js
Labels: V2, enhancement
