Repository VIAplanner/via-timetable, pull requests merged in 2020-05, with the labels that each got.

#119 Several front end enhancements
  packages/app/src/components/CourseSectionPicker.vue
  packages/app/src/components/Timetable.vue
  packages/app/src/components/TimetableEvent.vue
  packages/app/src/store/index.js
Labels: bug, enhancement

#122 Adjusted the spacing to accommodate adding am/pm to TimetableCourseCard and CourseSectionPicker
  packages/app/src/components/CourseSectionPicker.vue
  packages/app/src/components/TimetableCourseCard.vue
  packages/app/src/components/TimetableEvent.vue
Labels: clean up

#123 Fixed Warning Issue on Optimization Settings Component
  packages/app/src/components/OptimizationSettings.vue
Labels: bug
