Repository VIAplanner/via-timetable, pull requests merged in 2020-06, with the labels that each got.

#140 Search Bar Fix
  packages/app/src/components/CourseSearchBar.vue
  packages/app/src/components/OptimizationSettings.vue
  packages/app/src/components/SwitchSem.vue
  packages/app/src/components/SwitchTime.vue
  packages/app/src/components/Timetable.vue
  packages/app/src/components/TimetableEvent.vue
  packages/app/src/components/WeekdaySwitch.vue
  packages/app/src/store/index.js
  packages/app/src/views/Home.vue
Labels: bug, enhancement

#148 Display Half Hour Sections
  packages/app/src/components/ConflictPopUp.vue
  packages/app/src/components/CourseSectionPicker.vue
  packages/app/src/components/Timetable.vue
  packages/app/src/components/TimetableCourseCard.vue
  packages/app/src/components/TimetableEvent.vue
  packages/app/src/components/WeekdaySwitch.vue
  packages/app/src/store/index.js
Labels: bug, enhancement

#164 Fixed locked day issue
  packages/app/src/components/CourseSearchBar.vue
  packages/app/src/components/WeekdaySwitch.vue
  packages/app/src/views/Home.vue
Labels: bug

#166 Completed Landing page
  packages/app/src/App.vue
  packages/app/src/assets/img1.png
  packages/app/src/assets/img2.gif
  packages/app/src/assets/img3.gif
  packages/app/src/assets/slide1.gif
  packages/app/src/assets/slide2.gif
  packages/app/src/assets/slide3.gif
  packages/app/src/assets/slide4.gif
  packages/app/src/assets/slide5.gif
  packages/app/src/router/index.js
  packages/app/src/views/About.vue
  packages/app/src/views/Home.vue
  packages/app/src/views/Mobile.vue
Labels: enhancement

#167 Landing page fix
  packages/app/src/views/About.vue
Labels: bug

#170 Re-branding Complete
  packages/app/public/favicon.ico
  packages/app/src/assets/VIA-Planner-White.png
  packages/app/src/components/SwitchSem.vue
  packages/app/src/views/About.vue
  packages/app/src/views/Home.vue
Labels: enhancement

#172 Finished tutorial window
  packages/app/package-lock.json
  packages/app/package.json
  packages/app/public/index.html
  packages/app/src/assets/tut1.gif
  packages/app/src/assets/tut2.gif
  packages/app/src/assets/tut3.gif
  packages/app/src/assets/tut4.gif
  packages/app/src/components/Tutorial.vue
  packages/app/src/views/About.vue
  packages/app/src/views/Home.vue
  packages/app/src/views/Mobile.vue
Labels: enhancement

#177 New Docs Integration
  README.md
  VIA.png
  docs/CNAME
  docs/VIA.png
  docs/assets/css/0.styles.dcd73214.css
  docs/assets/img/Course_Selecting_State.0780452b.png
  docs/assets/img/Program_Choosing_state.a8110cda.png
  docs/assets/img/Timetable-journey.874c1c15.png
  docs/assets/img/backend-architecture.a26fc33b.png
  docs/assets/img/coursechosing.80b5906a.png
  docs/assets/img/error1.38a288a6.png
  docs/assets/img/error2.1552fc03.png
  docs/assets/img/figma_course_pic.a3c3a71b.png
  docs/assets/img/figma_pic.92ea85d9.png
  docs/assets/img/lock1.8ec839ae.png
  docs/assets/img/lock2.c237d63a.png
  docs/assets/img/playgroundEx1.a696f392.png
  docs/assets/img/playgroundEx2.2ec195ff.png
  docs/assets/img/playgroundEx3.726633e9.png
  docs/assets/img/search.83621669.svg
  docs/assets/img/timetable.f46bca2f.png
  docs/assets/img/timetableconstraint.bbe19910.png
  docs/assets/js/10.546c54d5.js
  docs/assets/js/11.17a6d447.js
  docs/assets/js/2.9352fab7.js
  docs/assets/js/3.6da44cdc.js
  docs/assets/js/4.7684fa53.js
  docs/assets/js/5.51ef2a75.js
  docs/assets/js/6.278a4744.js
  docs/assets/js/7.00de4f05.js
  docs/assets/js/8.2f391f9f.js
  docs/assets/js/9.0f2ff074.js
  docs/assets/js/app.ce8f3eda.js
  docs/config.html
  docs/course-api/index.html
  docs/course-guide/index.html
  docs/index.html
  docs/logo.png
  docs/timetable-planner/index.html
  docs/ui-components/favicon.ico
  docs/ui-components/iframe.html
  docs/ui-components/index.html
  docs/ui-components/main.8966690db7f99512cf85.bundle.js
  docs/ui-components/main.e2f6296bb9db17f5805d.bundle.js
  docs/ui-components/main.e2f6296bb9db17f5805d.bundle.js.map
  docs/ui-components/runtime~main.8bfece81a1ead32e094c.bundle.js
  docs/ui-components/runtime~main.e2f6296bb9db17f5805d.bundle.js
  docs/ui-components/runtime~main.e2f6296bb9db17f5805d.bundle.js.map
  docs/ui-components/sb_dll/storybook_ui-manifest.json
  docs/ui-components/sb_dll/storybook_ui_dll.LICENCE
  docs/ui-components/sb_dll/storybook_ui_dll.js
  docs/ui-components/static/media/materialdesignicons-webfont.63d2a595.woff
  docs/ui-components/static/media/materialdesignicons-webfont.7fb0e378.woff2
  docs/ui-components/static/media/materialdesignicons-webfont.a1a0ed86.eot
  docs/ui-components/static/media/materialdesignicons-webfont.fe1545ef.ttf
  docs/ui-components/vendors~main.60d89525918d54a0f971.bundle.js
  docs/ui-components/vendors~main.e2f6296bb9db17f5805d.bundle.js
  docs/ui-components/vendors~main.e2f6296bb9db17f5805d.bundle.js.LICENSE.txt
  docs/ui-components/vendors~main.e2f6296bb9db17f5805d.bundle.js.map
  packages/app/src/views/About.vue
Labels: clean up

#181 Final Cleanup for V1
  packages/app/package-lock.json
  packages/app/package.json
  packages/app/src/components/AboutBtn.vue
  packages/app/src/components/HelpDial.vue
  packages/app/src/components/TutorialBtn.vue
  packages/app/src/main.js
Labels: V1, clean up

#186 About Page Improvement
  packages/app/src/assets/about-background.jpg
  packages/app/src/views/About.vue
Labels: V1, enhancement

#187 About Page Improvement
  packages/app/src/views/About.vue
Labels: V1, enhancement

#188 Mobile View improvement
  packages/app/src/router/index.js
  packages/app/src/views/About.vue
  packages/app/src/views/Home.vue
  packages/app/src/views/Mobile.vue
Labels: clean up, enhancement

#191 Updated UTM Course Data
  packages/courses-scraper/api/node/scraper.js
  packages/courses-scraper/api/python/example_usage.py
  packages/courses-scraper/api/python/scraper.py
  packages/courses-scraper/api/python/uoftscraper.py
  packages/courses-scraper/api/python/uploader.py
  packages/courses-scraper/package-lock.json
  packages/courses-scraper/package.json
Labels: V2, critical

#195 Algorithm runs even with courses that don't have lectures
  packages/app/src/timetable-planner/index.js
Labels: bug, critical, enhancement

#197 Copyright info
  packages/app/src/views/About.vue
  packages/app/src/views/Home.vue
Labels: V2, enhancement

#198 Delivery methods
  packages/app/src/components/CourseSearchBar.vue
  packages/app/src/components/TimetableEvent.vue
  packages/app/src/store/index.js
  packages/app/src/timetable-planner/index.js
Labels: V2, bug

#202 Alpha Improvement
  packages/app/package-lock.json
  packages/app/package.json
  packages/app/src/components/AboutBtn.vue
  packages/app/src/components/ExportBtn.vue
  packages/app/src/components/HelpDial.vue
  packages/app/src/components/TutorialBtn.vue
  packages/app/src/main.js
  packages/app/src/store/index.js
  packages/app/src/views/About.vue
  packages/app/src/views/Home.vue
Labels: V2, enhancement

#204 Scraper Improvement
  packages/courses-scraper/api/node/scraper.js
  packages/courses-scraper/package-lock.json
  packages/courses-scraper/package.json
Labels: V2, enhancement

#207 Scraper Improvement
  packages/courses-scraper/api/node/scraper.js
  packages/courses-scraper/api/python/uploader.py
  packages/courses-scraper/package.json
Labels: V2, bug

#208 Lock Section Fix
  packages/app/src/components/CourseSectionPicker.vue
  packages/app/src/components/TimetableEvent.vue
  packages/app/src/store/index.js
Labels: V2, critical
