Repository VIAplanner/via-timetable, pull requests merged in 2020-02, with the labels that each got.

#9 Move docs to Monorepo
  packages/docs/.gitignore
  packages/docs/.vuepress/config.js
  packages/docs/README.md
  packages/docs/architecture.png
  packages/docs/config.md
  packages/docs/course-api/README.md
  packages/docs/course-api/backend-architecture.png
  packages/docs/course-guide/README.md
  packages/docs/docs/404.html
  packages/docs/docs/CNAME
  packages/docs/docs/assets/css/0.styles.a4aa4dff.css
  packages/docs/docs/assets/img/backend-architecture.a26fc33b.png
  packages/docs/docs/assets/img/search.83621669.svg
  packages/docs/docs/assets/js/10.c9edc631.js
  packages/docs/docs/assets/js/2.c4145938.js
  packages/docs/docs/assets/js/3.6be1c7af.js
  packages/docs/docs/assets/js/4.a3212f19.js
  packages/docs/docs/assets/js/5.be4c36a3.js
  packages/docs/docs/assets/js/6.918dd209.js
  packages/docs/docs/assets/js/7.144952ce.js
  packages/docs/docs/assets/js/8.dd15d632.js
  packages/docs/docs/assets/js/9.78e62699.js
  packages/docs/docs/assets/js/app.58e34285.js
  packages/docs/docs/config.html
  packages/docs/docs/course-api/index.html
  packages/docs/docs/course-guide/index.html
  packages/docs/docs/index.html
  packages/docs/docs/timetable-planner/index.html
  packages/docs/package-lock.json
  packages/docs/package.json
  packages/docs/timetable-planner/README.md
  packages/docs/timetable-planner/Timetable-journey.png
  packages/docs/timetable-planner/Timetableroadmap.png
  packages/docs/timetable-planner/coursechosing.png
  packages/docs/timetable-planner/courseguide_to_timetable.png
  packages/docs/timetable-planner/error1.png
  packages/docs/timetable-planner/error2.png
  packages/docs/timetable-planner/lock1.png
  packages/docs/timetable-planner/lock2.png
  packages/docs/timetable-planner/timetable.png
  packages/docs/timetable-planner/timetableconstraint.png
Labels: documentation, enhancement

#30 Roadmap of the Timetable Planner
  packages/docs/timetable-planner/README.md
  packages/programs-scraper/output/subjects/Language Teaching and Learning,.json
  packages/timetable-planner/planner-example.txt
Labels: documentation

#33 Edited the homepage to explain the goal of the project and merged the implementation section from old repo
  .gitignore
  packages/docs/README.md
Labels: enhancement
